### ISSUE TITLE
Error when doing `kid up`

### ISSUE THREAD

**Issue by RaeesBhatti** [vyshane/kid#11]
I got these errors when doing a `kid up` but everything seems to work fine.

```
error validating "STDIN": error validating data: unexpected type: object; if you choose to ignore these errors, turn validation off with --validate=false
error validating "STDIN": error validating data: [unexpected type: object, unexpected type: object, unexpected type: object, unexpected type: object, unexpected type: object, unexpected type: object, unexpected type: object, unexpected type: object, unexpected type: object, unexpected type: object, unexpected type: object]; if you choose to ignore these errors, turn validation off with --validate=false
error validating "STDIN": error validating data: [unexpected type: object, unexpected type: object, unexpected type: object, unexpected type: object, unexpected type: object]; if you choose to ignore these errors, turn validation off with --validate=false
```

**Comment by RaeesBhatti** [comment]
This makes `kid up` command hang in the terminal with all these errors. I'm not sure if this is the intended behaviour, but I would like it like it to finish and exit.

**Comment by vyshane** [comment]
The intended behaviour is for the command to finish and exit. What OS are you on? What version of Docker, and are you using Docker via Docker Machine?

**Comment by RaeesBhatti** [comment]
OS Version:

```
OS X El Capitan: 10.11.5 (15F34)
```

`docker --version`: (It's Docker for Mac)

```
Docker version 1.12.0-rc3, build 91e29e8, experimental
```

**Comment by RaeesBhatti** [comment]
I just found out that I can't do `kubectl create -f filename` without `--validate=false`, it throws the same error.

```
error validating "mongodb-deployment.yaml": error validating data: [unexpected type: object, unexpected type: object]; if you choose to ignore these errors, turn validation off with --validate=false
```

**Comment by vyshane** [comment]
What version of kubectl are you using?

**Comment by RaeesBhatti** [comment]
`kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"2", GitVersion:"v1.2.0", GitCommit:"5cb86ee022267586db386f62781338b0483733b3", GitTreeState:"clean"}

```

**Comment by vyshane** [comment]
kid master is currently using Kubernetes v1.3.0. Can you update your kubectl to that version and try again?

**Comment by RaeesBhatti** [comment]
Okay, I upgraded the `kubectl` and the error message is gone but the kid command it still stuck waiting.

```
$ kid up
Docker for Mac detected
Waiting for Kubernetes cluster to become available...
```

**Comment by vyshane** [comment]
What's the output of `kubectl config current-context`? Is your kubectl pointed to your local kid cluster (http://localhost:8080)?

**Comment by RaeesBhatti** [comment]
It was configure with `minikube` actually I delete `~/.kube` and it seems to be exiting with success with these warnings.

```
Docker for Mac detected
Waiting for Kubernetes cluster to become available...
Error from server: error when creating "STDIN": namespaces "kube-system" already exists
The Service "kube-dns" is invalid.
spec.clusterIP: Invalid value: "10.0.0.10": provided IP is already allocated
Connection to localhost port 31999 [tcp/*] succeeded!
Kubernetes cluster is up. The Kubernetes dashboard can be accessed via HTTP at port 31999 of your Docker host.
```

I tried `kid down` and confirmed all containers removed and again tried `kid up` and it didn't go away.

**Comment by vyshane** [comment]
It's okay to ignore these. They come up because k8s still has state from the previous run.

**Comment by RaeesBhatti** [comment]
Okay, thanks for your time
