### ISSUE TITLE
Question: OSX and docker beta for mac

### ISSUE THREAD

**Issue by joeblew99** [vyshane/kid#6]
With docket beta for mac there is no need for virualbox and all that goes along with it.

I am wondering if this repo has been tried with it. ?
I am willing to test and feedback issues and fix where needed since my main language is golang & kid looks very useful.

**Comment by vyshane** [comment]
Testing and feedback is always welcome :)

I've tried kid with Docker Beta (1.11.1-beta13). It currently does not work. Relevant discussions: 
- kubernetes/kubernetes#25520.
- [Beta 9 and localhost connection via net=host](https://forums.docker.com/t/beta-9-and-localhost-connection-via-net-host/10471)

**Comment by FrenchBen** [comment]
Both threads are fairly different - The forum post is incorrect use of docker networking, causing some issue with communication.
The kubernetes thread is misleading as a LOT of services are being replaced to get the kublet working. 
When I went through the Getting started guide, all of the commands looked like they were running from a regular Mac OSX when really they need to be ran from within the VM. 
How is `kid` dealing with this?

**Comment by vyshane** [comment]
@FrenchBen `kid` launches Kubernetes in Docker [in the same way](https://github.com/vyshane/kid/blob/master/kid#L301) that the Getting Started Guide does.

**Comment by FrenchBen** [comment]
@vyshane How does this part of code work?

```
        --volume=/:/rootfs:ro \
        --volume=/sys:/sys:ro \
        --volume=/var/lib/docker/:/var/lib/docker:rw \
        --volume=/var/lib/kubelet/:/var/lib/kubelet:rw \
        --volume=/var/run:/var/run:rw \
```

Most of these endpoints do not exist on OSX?

**Comment by danisla** [comment]
I was able to get it working with Docker for Mac 1.11.1-beta13 using a few hacks. 

I set `native/port-forwarding = false` using the `pinata` command and then using a ssh container to port forward in host mode to the kubernetes API because for some reason I could not access port `8080` at the host IP `192.168.64.2`. 

I have the changes that automate all of the Docker for Mac specific actions on [my branch](https://github.com/danisla/kid/commit/d8c64e4b91bef290057605e40c3e4a579849e26c) if anyone is interested or wants to contribute.

**Comment by joeblew99** [comment]
does it still work on a mac using virtual box for docker ?

**Comment by danisla** [comment]
@joeblew99 the latest commits on my [docker-mac](https://github.com/danisla/kid/tree/docker-mac) branch are compatible with docker-machine too. 

I also fixed an annoying issue with configmaps not working because the `shared` flag is not set on the `/var/lib/kubelet` mount.

**Comment by joeblew99** [comment]
i wil try it out

**Comment by joeblew99** [comment]
works 👍 are you gonna PR it ?

**Comment by danisla** [comment]
Glad to hear, yeah I'll submit the PR here in the next day or so.

**Comment by joeblew99** [comment]
closing...
