### ISSUE TITLE
remove pindata in docker for mac

### ISSUE THREAD

**Issue by amoAHCP** [vyshane/kid#9]
"pindata" was removed from Docker beta 16 for Mac. According to https://news.ycombinator.com/item?id=11567442 localhost should be used by default

**Comment by vyshane** [comment]
@danisla do you know what needs to be done to support Docker 1.12 beta for Mac?

**Comment by danisla** [comment]
@vyshane yes I've been working on this and found a new way around the `net=host` issue, PR is on the way.
